excluded:
 - .build/
 - build/
 - Packages/.build/

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - file_length
  - force_cast
  - function_body_length
  - line_length
  - nesting
  - type_name
  - force_try
  - cyclomatic_complexity
  - trailing_comma
  - large_tuple
  - multiple_closures_with_trailing_closure
  - fallthrough
  - no_fallthrough_only
  - switch_case_alignment
  - inclusive_language
  - xctfail_message

colon:
  flexible_right_spacing: true
